### ISSUE TITLE
build the sdk with aac

### ISSUE THREAD

**Issue by Zevolusion** [aws-samples/amazon-kinesis-video-streams-media-interface#22]
It occur error, after I set USE_AUDIO_AAC to 1 
The toolchain is mips-gcc472-glibc216-32bit
![image](https://user-images.githubusercontent.com/16457119/149271480-f5704591-c168-4327-a692-c192c34ba5ea.png)
![image](https://user-images.githubusercontent.com/16457119/149271493-6b41b513-52c4-4424-94b1-85e6a8228e41.png)

**Comment by weichihl** [comment]
The fix has been merged with this PR: [https://github.com/aws-samples/amazon-kinesis-video-streams-media-interface/pull/21](https://github.com/aws-samples/amazon-kinesis-video-streams-media-interface/pull/21)

Could you try again? Thanks.

**Comment by codingspirit** [comment]
@Zevolusion We will look into this build error but the current implementation of T31 audio capturer doesn't support AAC since T31 doesn't provide any AAC encoder in their board SDK. A software encoder might be an approach.

**Comment by codingspirit** [comment]
Hi @Zevolusion #28 should fix this build error, but you still need to attach a software AAC encoder since T31 doesn't provide a hardware one.
