### ISSUE TITLE
[QUESTION]KVS和WEBRTC内存使用情况

### ISSUE THREAD

**Issue by yy-arya** [aws-samples/amazon-kinesis-video-streams-media-interface#95]
**Describe the questions**
请问这个版本对Ingennic T31的设备上KVS和WEBRTC服务的内存优化情况如何？
包括库和应用所需FLASH的内存大小，及运行所占内存的大小。
请问有相关数据吗？

**Target platform**
The target platform you are using.

**Commit Id**
The commit id you are using.
i.e 6f3d3eeccdcf5a36ad63d617712ff732714d40e3

**Additional context**

**Comment by codingspirit** [comment]
Ram usage has strong correlation with your board configurations. We can't give estimated RAM/Flash usage report to a specific platform since user might get different results on their boards.
