### ISSUE TITLE
Duplicate declaration of const?

### ISSUE THREAD

**Issue by cwestergren** [aws-samples/amazon-kinesis-video-streams-media-interface#99]
**Describe the build issue**
Some code seems to include duplicate const declaration like;

VideoCapturerStatus videoCapturerGetStatus(const VideoCapturerHandle **const** handle)
{
    if (!handle) {
        return VID_CAP_STATUS_NOT_READY;
    }

    FILE_HANDLE_GET(handle);
    return fileHandle->status;
}

**Target platform**
Linux

**Commit id**
The commit id you are using.
47c3e59d9d14df0be7e8532279646c7a63c5b6de

**Comment by codingspirit** [comment]
It indicates that the pointer and the value it points to should not be modified. It's reasonable to do so in a `get` method because we don't want `handle` modified inside `get` function call.

Please let me know if your compiler is complaining about this.

**Comment by codingspirit** [comment]
Closing stale issue.

**Comment by cwestergren** [comment]
@codingspirit sorry for delay on this response, good that you closed the issue. I had an environment issue causing this build error. Solved now.

**Comment by codingspirit** [comment]
@cwestergren We decide to remove the second const qualifier since c++ toolchains complain about this. See #101 for more details
